branch: master
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version} [skip ci] ***NO_CI***\n\n${nextRelease.notes}"
  - - "@semantic-release/exec"
    - successCmd: |
        echo '##vso[task.setvariable variable=nextRelease]${nextRelease.version}